global:
  scrape_interval: 10s # 10초마다 수집

scrape_configs:
  - job_name: 'token-ledger-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080'] # ECS 내부에서는 localhost로 통신합니다!